swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /ciudad/:
    get:
      tags:
      - ciudad
      description: get Ciudad
      operationId: CiudadController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Ciudad'
        "403":
          description: ""
    post:
      tags:
      - ciudad
      description: create Ciudad
      operationId: CiudadController.Post
      parameters:
      - in: body
        name: body
        description: body for Ciudad content
        required: true
        schema:
          $ref: '#/definitions/models.Ciudad'
      responses:
        "201":
          description: '{int} models.Ciudad'
        "403":
          description: body is empty
  /ciudad/{id}:
    get:
      tags:
      - ciudad
      description: get Ciudad by id
      operationId: CiudadController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Ciudad'
        "403":
          description: :id is empty
    put:
      tags:
      - ciudad
      description: update the Ciudad
      operationId: CiudadController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Ciudad content
        required: true
        schema:
          $ref: '#/definitions/models.Ciudad'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Ciudad'
        "403":
          description: :id is not int
    delete:
      tags:
      - ciudad
      description: delete the Ciudad
      operationId: CiudadController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /pais/:
    get:
      tags:
      - pais
      description: get Pais
      operationId: PaisController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Pais'
        "403":
          description: ""
    post:
      tags:
      - pais
      description: create Pais
      operationId: PaisController.Post
      parameters:
      - in: body
        name: body
        description: body for Pais content
        required: true
        schema:
          $ref: '#/definitions/models.Pais'
      responses:
        "201":
          description: '{int} models.Pais'
        "403":
          description: body is empty
  /pais/{id}:
    get:
      tags:
      - pais
      description: get Pais by id
      operationId: PaisController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Pais'
        "403":
          description: :id is empty
    put:
      tags:
      - pais
      description: update the Pais
      operationId: PaisController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Pais content
        required: true
        schema:
          $ref: '#/definitions/models.Pais'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Pais'
        "403":
          description: :id is not int
    delete:
      tags:
      - pais
      description: delete the Pais
      operationId: PaisController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.Ciudad:
    title: Ciudad
    type: object
    properties:
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      PaisId:
        $ref: '#/definitions/models.Pais'
  models.Pais:
    title: Pais
    type: object
    properties:
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
tags:
- name: pais
  description: |
    PaisController operations for Pais
- name: ciudad
  description: |
    CiudadController operations for Ciudad
