swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /detalle_partido/:
    get:
      tags:
      - detalle_partido
      description: get DetallePartido
      operationId: DetallePartidoController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.DetallePartido'
        "403":
          description: ""
    post:
      tags:
      - detalle_partido
      description: create DetallePartido
      operationId: DetallePartidoController.Post
      parameters:
      - in: body
        name: body
        description: body for DetallePartido content
        required: true
        schema:
          $ref: '#/definitions/models.DetallePartido'
      responses:
        "201":
          description: '{int} models.DetallePartido'
        "403":
          description: body is empty
  /detalle_partido/{id}:
    get:
      tags:
      - detalle_partido
      description: get DetallePartido by id
      operationId: DetallePartidoController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.DetallePartido'
        "403":
          description: :id is empty
    put:
      tags:
      - detalle_partido
      description: update the DetallePartido
      operationId: DetallePartidoController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for DetallePartido content
        required: true
        schema:
          $ref: '#/definitions/models.DetallePartido'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.DetallePartido'
        "403":
          description: :id is not int
    delete:
      tags:
      - detalle_partido
      description: delete the DetallePartido
      operationId: DetallePartidoController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /partido/:
    get:
      tags:
      - partido
      description: get Partido
      operationId: PartidoController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Partido'
        "403":
          description: ""
    post:
      tags:
      - partido
      description: create Partido
      operationId: PartidoController.Post
      parameters:
      - in: body
        name: body
        description: body for Partido content
        required: true
        schema:
          $ref: '#/definitions/models.Partido'
      responses:
        "201":
          description: '{int} models.Partido'
        "403":
          description: body is empty
  /partido/{id}:
    get:
      tags:
      - partido
      description: get Partido by id
      operationId: PartidoController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Partido'
        "403":
          description: :id is empty
    put:
      tags:
      - partido
      description: update the Partido
      operationId: PartidoController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Partido content
        required: true
        schema:
          $ref: '#/definitions/models.Partido'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Partido'
        "403":
          description: :id is not int
    delete:
      tags:
      - partido
      description: delete the Partido
      operationId: PartidoController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.DetallePartido:
    title: DetallePartido
    type: object
    properties:
      Equipo1Id:
        type: integer
        format: int64
      Equipo2Id:
        type: integer
        format: int64
      GolesLocal:
        type: integer
        format: int64
      GolesVisitante:
        type: integer
        format: int64
      Id:
        type: integer
        format: int64
      IdPartido:
        $ref: '#/definitions/models.Partido'
  models.Partido:
    title: Partido
    type: object
    properties:
      Ciudad:
        type: integer
        format: int64
      Fecha:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
tags:
- name: partido
  description: |
    PartidoController operations for Partido
- name: detalle_partido
  description: |
    DetallePartidoController operations for DetallePartido
